version: '3.8'

services:
  app:
    image: tool-content-be:${BRANCH_NAME:-latest}
    container_name: ${APP_NAME}
#    build:
#      context: .
#      dockerfile: Dockerfile
      # Chú ý: bạn có thể gỡ `build` nếu Jenkins đã build trước và chỉ `image:` là đủ
    ports:
      - "3000:${APP_PORT}"
    environment:
      - DB_HOST=db
      - DB_PORT=${MYSQL_PORT}
      - DB_USER=root
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
    depends_on:
      - db  
    networks:
      - backend

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend

networks:
  backend:

volumes:
  mysql_data:
