version: '3.8'

services:
  app:
    image: tool-content-be:${BRANCH_NAME:-latest}
    container_name: ${APP_NAME}
    ports:
      - "${APP_PORT}"
    environment:
      - DB_HOST=db
      - DB_PORT=${MYSQL_PORT}
      - DB_USER=root
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend

  db:
    image: mysql:8.0
    container_name: mysql-db-${BRANCH_NAME}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 20

  nginx:
    image: nginx:alpine
    container_name: nginx-${BRANCH_NAME}
    ports:
      - "80:80"
    volumes:
      - ./nginx/template.conf:/etc/nginx/templates/default.conf.template
      - nginx_conf:/etc/nginx/conf.d
    networks:
      - backend
    depends_on:
      - app
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  backend:

volumes:
  mysql_data:
  nginx_conf:
